spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pride_db
    username: pride_user
    password: pride1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090

ai-server:
  base-url: http://localhost:8000